spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 10080
---
spring:
  config:
    activate:
      on-profile: real

---
spring:
  config:
    activate:
      on-profile: alpha, local

---
spring:
  config:
    activate:
      on-profile: local

